### ISSUE TITLE
Add option to upload files for public access

### ISSUE THREAD

**Issue by gemblerz** [sagecontinuum/sage-cli#8]
When uploading files to a bucket, the cli tool needs to support an option to specify whether the files are accessible by public or private only. This may also be related to the bucket creation operation -- making a bucket public so any files uploaded in the bucket will be visible by public.

It may be useful to set public access by default and provide `-private` option to make files and buckets private
```bash
# upload my-file as private
$ sage-cli.py storage files upload --private ${BUCKET_ID} my-file
# create a bucket as private
$ sage-cli.py storage bucket create --private --name my-bucket --datetype model
```

**Comment by wgerlach** [comment]
done
